# forge-canary: FORGE-CANARY-C3A4D0A724B2C1B4ABB13DD5F51313F5
# GENERATED by solution/recompute.py from solution/grounding.yaml. Do not edit by hand.
"""Compiled rubric. One test per compiled rubric item, reconciled by identifier set equality."""

from __future__ import annotations

import json
import os
import pathlib

import pytest

REWARD_PATH = pathlib.Path(os.environ.get("REWARD_PATH", "/logs/verifier/reward.json"))


@pytest.fixture(scope="module")
def reward() -> dict:
    if not REWARD_PATH.exists():
        pytest.fail(f"reward document absent at {REWARD_PATH}")
    return json.loads(REWARD_PATH.read_text())


def _checker(reward: dict, checker_id: str) -> dict:
    for entry in reward["checkers"]:
        if entry["checker_id"] == checker_id:
            return entry
    pytest.fail(f"checker {checker_id} absent from reward document")


def test_compiled_C1_construction_size_value(reward: dict) -> None:
    entry = _checker(reward, "C1_construction_size_value")
    assert entry["passed"] is True, entry["reason"]


def test_compiled_C2_reference_construction_absence(reward: dict) -> None:
    entry = _checker(reward, "C2_reference_construction_absence")
    assert entry["passed"] is True, entry["reason"]


def test_compiled_C_M1_geometry_parameter_identity(reward: dict) -> None:
    entry = _checker(reward, "C_M1_geometry_parameter_identity")
    assert entry["passed"] is True, entry["reason"]


def test_compiled_C_M2_property_predicate_binding(reward: dict) -> None:
    entry = _checker(reward, "C_M2_property_predicate_binding")
    assert entry["passed"] is True, entry["reason"]


def test_compiled_C3_certificate_invariant(reward: dict) -> None:
    entry = _checker(reward, "C3_certificate_invariant")
    assert entry["passed"] is True, entry["reason"]


def test_compiled_C4_attempt_ordering(reward: dict) -> None:
    entry = _checker(reward, "C4_attempt_ordering")
    assert entry["passed"] is True, entry["reason"]


def test_compiled_C5_injection_absence(reward: dict) -> None:
    entry = _checker(reward, "C5_injection_absence")
    assert entry["passed"] is True, entry["reason"]


def test_compiled_C6_silent_degeneracy_divergence(reward: dict) -> None:
    entry = _checker(reward, "C6_silent_degeneracy_divergence")
    assert entry["passed"] is True, entry["reason"]


def test_compiled_C_M4_translation_anchor_binding(reward: dict) -> None:
    entry = _checker(reward, "C_M4_translation_anchor_binding")
    assert entry["passed"] is True, entry["reason"]


def test_compiled_C_M5_digest_join_binding(reward: dict) -> None:
    entry = _checker(reward, "C_M5_digest_join_binding")
    assert entry["passed"] is True, entry["reason"]


def test_compiled_C_M6_pair_sum_order_binding(reward: dict) -> None:
    entry = _checker(reward, "C_M6_pair_sum_order_binding")
    assert entry["passed"] is True, entry["reason"]
