# forge-canary: FORGE-CANARY-837861982023138C90B2C0024F036FE0
# GENERATED by seed/forge/scaffold.py from seed/contract.yaml. Do not edit by hand.
"""Recomputes every generated artifact for this bundle from solution/grounding.yaml alone."""

from __future__ import annotations

import json
import pathlib

import yaml

HERE = pathlib.Path(__file__).resolve().parent
BUNDLE = HERE.parent

GENERATED_BANNER = "<!-- GENERATED by solution/recompute.py from solution/grounding.yaml. Do not edit by hand. -->"
PY_BANNER = "# GENERATED by solution/recompute.py from solution/grounding.yaml. Do not edit by hand."


def load() -> dict:
    return yaml.safe_load((HERE / "grounding.yaml").read_text())


def compiled_item_id(checker_id: str) -> str:
    return f"compiled_{checker_id}"


def test_name(checker_id: str) -> str:
    return f"test_{compiled_item_id(checker_id)}"


def build_truth(grounding: dict) -> str:
    checkers = grounding["checkers"]
    mutations = {m["mutation_id"]: m for m in grounding["mutations"]}
    deliverables = {d["deliverable_id"]: d for d in grounding["deliverables"]}
    measured = grounding["parameters"]["measured"]

    lines = [GENERATED_BANNER, "", "# TRUTH", ""]
    lines.append(
        f"Golden path for {grounding['slot_id']}. One step per checker identifier. The step identifier set equals the checker identifier set exactly, and the set of deliverables named across the steps equals the declared deliverable set exactly."
    )
    lines.append("")
    lines.append(
        f"The reference solution reaches score {measured['reference_score']} at weighted pass fraction {measured['reference_fraction_holdout']} over the held out suite, inside the declared target band {measured['target_band'][0]} to {measured['target_band'][1]}. The starter artifact reaches {measured['starter_score_pre_mutation']} before the registries move and {measured['starter_score_post_mutation']} after the silent calling convention repin."
    )
    lines.append("")

    for index, checker in enumerate(checkers, start=1):
        deliverable = deliverables[checker["deliverable_id"]]
        lines.append(f"## Step {index}: {checker['checker_id']}")
        lines.append("")
        lines.append(f"- action: {checker['action']}")
        lines.append(f"- resulting state: {checker['resulting_state']}")
        lines.append(f"- deliverable: {checker['deliverable_id']} at {deliverable['filename']}")
        for mutation_id in sorted(mutations):
            survives = checker[f"survives_{mutation_id.lower()}"]
            verdict = "survives unchanged" if survives else "must be reworked"
            lines.append(
                f"- mutation {mutation_id} at turn {mutations[mutation_id]['turn']}: {verdict}"
            )
        lines.append(f"- observed by checker: {checker['checker_id']} of type {checker['checker_type']}")
        lines.append(f"- criterion: {checker['criterion_literal']}")
        lines.append("")

    lines.append("## Reconciliation")
    lines.append("")
    lines.append(f"- step identifiers: {', '.join(c['checker_id'] for c in checkers)}")
    lines.append(f"- deliverables named: {', '.join(sorted({c['deliverable_id'] for c in checkers}))}")
    lines.append(f"- deliverables declared: {', '.join(sorted(deliverables))}")
    lines.append("")
    return "\n".join(lines)


def build_rubrics(grounding: dict) -> dict:
    rubric = grounding["rubric"]
    items = []
    for checker in grounding["checkers"]:
        items.append(
            {
                "id": compiled_item_id(checker["checker_id"]),
                "dimension": rubric["compiled_dimension"],
                "weight": rubric["compiled_weight"],
                "evaluation_target": checker["deliverable_id"],
                "criterion": checker["criterion_literal"],
                "judgment": rubric["compiled_judgment"],
                "evidence": rubric["compiled_evidence"],
                "mode": "compiled",
            }
        )
    for judged in rubric["judged_items"]:
        items.append(
            {
                "id": judged["id"],
                "dimension": judged["dimension"],
                "weight": judged["weight"],
                "evaluation_target": judged["evaluation_target"],
                "criterion": judged["criterion"],
                "judgment": judged["judgment"],
                "evidence": judged["evidence"],
                "mode": "judged",
            }
        )
    compiled = sum(1 for item in items if item["mode"] == "compiled")
    return {
        "schema_version": 1,
        "slot_id": grounding["slot_id"],
        "compilation_floor": rubric["compilation_floor"],
        "compiled_fraction": round(compiled / len(items), 6),
        "items": items,
    }


def build_test_output(grounding: dict) -> str:
    lines = [
        PY_BANNER,
        '"""Compiled rubric. One test per compiled rubric item, reconciled by identifier set equality."""',
        "",
        "from __future__ import annotations",
        "",
        "import json",
        "import os",
        "import pathlib",
        "",
        "import pytest",
        "",
        'REWARD_PATH = pathlib.Path(os.environ.get("REWARD_PATH", "/logs/verifier/reward.json"))',
        "",
        "",
        '@pytest.fixture(scope="module")',
        "def reward() -> dict:",
        "    if not REWARD_PATH.exists():",
        '        pytest.fail(f"reward document absent at {REWARD_PATH}")',
        "    return json.loads(REWARD_PATH.read_text())",
        "",
        "",
        "def _checker(reward: dict, checker_id: str) -> dict:",
        '    for entry in reward["checkers"]:',
        '        if entry["checker_id"] == checker_id:',
        "            return entry",
        '    pytest.fail(f"checker {checker_id} absent from reward document")',
        "",
    ]
    for checker in grounding["checkers"]:
        lines.append("")
        lines.append(f"def {test_name(checker['checker_id'])}(reward: dict) -> None:")
        lines.append(f'    entry = _checker(reward, "{checker["checker_id"]}")')
        lines.append('    assert entry["passed"] is True, entry["reason"]')
        lines.append("")
    return "\n".join(lines)


def reconcile(grounding: dict) -> None:
    checker_ids = [c["checker_id"] for c in grounding["checkers"]]
    if len(set(checker_ids)) != len(checker_ids):
        raise SystemExit("duplicate checker identifier in grounding")
    declared = {d["deliverable_id"] for d in grounding["deliverables"]}
    named = {c["deliverable_id"] for c in grounding["checkers"]}
    if named != declared:
        raise SystemExit(f"deliverable set mismatch: named {sorted(named)} declared {sorted(declared)}")
    for checker in grounding["checkers"]:
        literal = checker["criterion_literal"]
        if not isinstance(literal, str) or len(literal.split()) < 12:
            raise SystemExit(f"criterion literal is not a frozen requirement for {checker['checker_id']}")
        for field in ("action", "resulting_state", "survives_m1", "survives_m2"):
            if field not in checker:
                raise SystemExit(f"golden path field {field} absent for {checker['checker_id']}")
    for control in grounding["controls"]:
        if not (BUNDLE / control["control_path"]).exists():
            raise SystemExit(f"control module absent: {control['control_path']}")


def main() -> int:
    grounding = load()
    reconcile(grounding)
    (HERE / "TRUTH.md").write_text(build_truth(grounding))
    (HERE / "rubrics.json").write_text(json.dumps(build_rubrics(grounding), indent=2, sort_keys=True) + "\n")
    (BUNDLE / "tests" / "test_output.py").write_text(build_test_output(grounding))
    print(
        json.dumps(
            {
                "checkers": len(grounding["checkers"]),
                "controls": len(grounding["controls"]),
                "rubric_items": len(build_rubrics(grounding)["items"]),
                "compiled_fraction": build_rubrics(grounding)["compiled_fraction"],
            },
            sort_keys=True,
        )
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
